<?php
/**
 * Copyright (c) Ratepay GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// @codingStandardsIgnoreFile
/**
 * @var \RatePAY\Payment\Block\Info\Info $block
 * @see \RatePAY\Payment\Block\Info\Info
 */
?>
<p><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></p>
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
<p><?php echo 'Transaction-Id: ' . $block->getTransactionId()?></p>
<p><?php echo 'Descriptor: ' . $block->getDescriptor()?></p>
<?php endif ?>