<?php

/** @var \RatePay\Payment\Block\Form\Installment $block */

$code = $block->escapeHtml($block->getMethodCode());

?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */ echo $code; ?>" style="display:none">
    <?php if ($block->isPhoneVisible()): ?>
        <div class="admin__field _required">
            <label class="label admin__field-label" for="<?php /* @noEscape */ echo $code; ?>_iban">
                <span><?php echo $block->escapeHtml(__('Phone')); ?></span>
            </label>
            <div class="admin__field-control control">
                <input id="<?php /* @noEscape */ echo $code; ?>_iban" name="payment[rp_phone]" value="<?php echo $block->getInfoData('rp_phone'); ?>">
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->isDobVisible()): ?>
        <div class="admin__field _required">
            <label class="label admin__field-label" for="<?php /* @noEscape */ echo $code; ?>_dob_day">
                <span><?php echo $block->escapeHtml(__('Birthday')); ?></span>
            </label>
            <div class="admin__field-control control">
                <input type="text" placeholder="DD" size="3" maxlength="2" id="<?php /* @noEscape */ echo $code; ?>_dob_day" name="payment[rp_dob_day]" value="<?php echo $block->getInfoData('rp_dob_day'); ?>">
                <input type="text" placeholder="MM" size="3" maxlength="2" id="<?php /* @noEscape */ echo $code; ?>_dob_month" name="payment[rp_dob_month]" value="<?php echo $block->getInfoData('rp_dob_month'); ?>">
                <input type="text" placeholder="YYYY" size="5" maxlength="4" id="<?php /* @noEscape */ echo $code; ?>_dob_year" name="payment[rp_dob_year]" value="<?php echo $block->getInfoData('rp_dob_year'); ?>">
            </div>
        </div>
    <?php else: ?>
        <div class="admin__field">
            <label><?php echo __('Date of Birth'); ?></label>
            <span><?php echo $block->getBirthday(); ?></span>
            <input type="hidden" name="payment[rp_dob_day]" value="<?php echo $block->getBirthdayPart('d'); ?>">
            <input type="hidden" name="payment[rp_dob_month]" value="<?php echo $block->getBirthdayPart('m'); ?>">
            <input type="hidden" name="payment[rp_dob_year]" value="<?php echo $block->getBirthdayPart('Y'); ?>">
        </div>
    <?php endif; ?>
    <div>
        <?php echo __('ratepay_terms_block_1'); ?>
        <a target="_blank" href="https://www.ratepay.com/zgb-dse"><?php echo __('ratepay_terms_block_2'); ?></a>
        <?php echo __('ratepay_terms_block_3'); ?>
    </div><br>
    <div class="rpContainer">
        <?php if ($block->hasAllowedMonths()): ?>
            <div class="admin__field">
                <?php echo __('rp_calculation_intro_part1'); ?>
                <b><?php echo __('rp_calculation_intro_part2'); ?></b>
                <?php echo __('rp_calculation_intro_part3'); ?>
                <b><?php echo __('rp_calculation_intro_part4'); ?></b>
            </div>
            <div class="admin__field" style="border: 1px solid black; padding: 10px;margin-bottom: 15px;">
                <div class="admin__field" style="margin-top: 0;">
                    <label class="label admin__field-label" for="<?php echo $code.'-time'; ?>">
                        <span><?php echo $block->escapeHtml(__('rp_runtime_description')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <select id="<?php echo $code.'-time'; ?>" onchange="updateInstallmentPlanRuntime(ratePayRestUrl, ratePayGrandTotal, '<?php echo $code; ?>')">
                            <option value=""><?php echo __('-- Please select runtime --'); ?></option>
                            <?php foreach ($block->getAllowedMonths() as $value): ?>
                                <option value="<?php echo $value; ?>"><?php echo $value; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="admin__field" style="text-align: center;">
                    <b><?php echo __('---OR---'); ?></b>
                </div>
                <div class="admin__field">
                    <label class="label admin__field-label" for="<?php echo $code.'-rate'; ?>">
                        <span><?php echo $block->escapeHtml(__('rp_rate_description')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input id="<?php echo $code.'-rate'; ?>" type="text" class="form-control" aria-label="Amount" /><br>
                        <span class="input-group-btn">
                            <button id="<?php echo $code.'_Input-button'; ?>" type="button" onclick="updateInstallmentPlanAmount(ratePayRestUrl, ratePayGrandTotal, '<?php echo $code; ?>')" class="btn btn-default" role="group">
                                <?php echo __('rp_calculate_rate'); ?>
                            </button>
                        </span>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <input id="<?php echo $code.'-runtime'; ?>" type="hidden" value="" />
        <div class="rpClear"></div>
        <div id="<?php echo $code.'_ContentSwitch'; ?>" class="ratepay-ContentSwitch" style="display: none;">
            <div class="ratepay-ChooseRuntime">
                <div id="<?php echo $code.'_ResultContainer'; ?>">

                </div>
            </div>
        </div>
        <div id="<?php echo $code.'_Notification'; ?>"></div>
    </div>
    <?php if ($block->isSepaBlockVisible() === true): ?>
        <ul style="list-style: none; margin-bottom: 15px; border: 1px solid #BDBDBD; padding-left: 4px;">
            <li><label><span><?php echo __('Ratepay address'); ?></span></label></li>
            <li><label><span><?php echo __('Creditor'); ?></span><span><?php echo __('Ratepay Creditor ID'); ?></span></label></li>
            <li><label><span><?php echo __('Mandate'); ?></span><span><?php echo __('Mandate Ref'); ?></span></label></li>
        </ul>
        <ul style="list-style: none;">
            <li style="margin-bottom: 15px;"><label><b><span><?php echo __('insert bankdata'); ?></span></b></label></li>
            <li><label><span><?php echo __('Account holder'); ?></span></label></li>
            <li><label><i><span><?php echo $block->getBillingName(); ?></span></i></label></li>
        </ul>
        <div class="admin__field _required" style="margin-left: -30px;">
            <label class="label admin__field-label" for="<?php /* @noEscape */ echo $code; ?>_iban">
                <span><?php echo $block->escapeHtml(__('IBAN')); ?></span>
            </label>
            <div class="admin__field-control control">
                <input type="text" size="35" id="<?php /* @noEscape */ echo $code; ?>_iban" name="payment[rp_iban]" value="<?php echo $block->getInfoData('rp_iban'); ?>">
            </div>
        </div>
        <a id="<?php echo $code; ?>_sepa_agreement_link" onclick="showAgreement('<?php echo $code; ?>')"><?php echo __('ratepay_directdebit_sepa_link'); ?></a>
        <table>
            <tbody style="display:none;" id="<?php echo $code; ?>_sepa_agreement">
            <tr>
                <td style="padding:10px 0;">
                        <span class="required ratepayagreement">
                            <?php echo __('ratepay_directdebit_sepa_terms_block_1'); ?>
                            <?php echo __('Ratepay address'); ?>
                            <?php echo __('ratepay_directdebit_sepa_terms_block_2'); ?>
                            <?php echo __('ratepay_directdebit_sepa_terms_block_3'); ?>
                        </span>
                </td>
            </tr>
            <tr>
                <td style="padding:10px 0;">
                    <br/>
                    <span style="font-weight:bold;"><?php echo __('ratepay_directdebit_sepa_notice_block_1'); ?></span><br/>
                    <?php echo __('ratepay_directdebit_sepa_notice_block_2'); ?><br/>
                    <?php echo __('ratepay_directdebit_sepa_notice_block_3'); ?>
                </td>
            </tr>
            </tbody>
        </table><br>
    <?php endif; ?>
    <input type="submit" name="Submit" style="display: none;">
</fieldset>
<script>
    /**
     * Disable card server validation in admin
     */
    require(["Magento_Sales/order/create/form"], function () {
        order.addExcludedPaymentMethod('<?php /* @noEscape */ echo $code; ?>');
    });

    var ratePayRestUrl = '<?php echo $block->getRestUrl(); ?>';
    var ratePayGrandTotal = <?php echo $block->getQuoteGrandTotal(); ?>;

    <?php if ($block->hasAllowedMonths() === false): ?>
        require([
            'jquery'
        ], function ($) {
            $(document).ready(function() {
                updateInstallmentPlan(ratePayRestUrl, 'time', '0', ratePayGrandTotal, '<?php echo $code; ?>')
            });
        });
    <?php endif; ?>

    ///@TODO: Validierung
    var isInstallmentPlanSet = false;


</script>