<?php

/** @var \RatePay\Payment\Block\Form\Installment $block */

$code = $block->escapeHtml($block->getMethodCode());

$ratePayGrandTotal = $block->getQuoteGrandTotal();

$dobDisplay = '';
$b2bEnabled = $block->getIsB2BModeEnabled();
if ($b2bEnabled === true) {
    $dobDisplay = 'display: none;';
}

?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */ echo $code; ?>" style="display:none">
    <?php if ($block->isPhoneVisible()): ?>
        <div class="admin__field _required">
            <label class="label admin__field-label" for="<?php /* @noEscape */ echo $code; ?>_phone">
                <span><?php echo $block->escapeHtml(__('Phone')); ?></span>
            </label>
            <div class="admin__field-control control">
                <input id="<?php /* @noEscape */ echo $code; ?>_phone" name="payment[rp_phone]" value="<?php echo $block->getInfoData('rp_phone'); ?>">
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->isDobVisible()): ?>
        <div class="admin__field _required" id="ratepay_<?php echo $code; ?>_birthday" style="margin-left:-30px;<?php echo $dobDisplay; ?>">
            <label class="label admin__field-label" for="<?php /* @noEscape */ echo $code; ?>_dob_day">
                <span><?php echo $block->escapeHtml(__('Birthday')); ?></span>
            </label>
            <div class="admin__field-control control">
                <input type="text" placeholder="DD" size="3" maxlength="2" id="<?php /* @noEscape */ echo $code; ?>_dob_day" name="payment[rp_dob_day]" value="<?php echo $block->getInfoData('rp_dob_day'); ?>">
                <input type="text" placeholder="MM" size="3" maxlength="2" id="<?php /* @noEscape */ echo $code; ?>_dob_month" name="payment[rp_dob_month]" value="<?php echo $block->getInfoData('rp_dob_month'); ?>">
                <input type="text" placeholder="YYYY" size="5" maxlength="4" id="<?php /* @noEscape */ echo $code; ?>_dob_year" name="payment[rp_dob_year]" value="<?php echo $block->getInfoData('rp_dob_year'); ?>">
            </div>
        </div>
    <?php else: ?>
        <div class="admin__field" id="ratepay_<?php echo $code; ?>_birthday" style="<?php echo $dobDisplay; ?>">
            <label><?php echo __('Date of Birth'); ?></label>
            <span><?php echo $block->getBirthday(); ?></span>
            <input type="hidden" name="payment[rp_dob_day]" value="<?php echo $block->getBirthdayPart('d'); ?>">
            <input type="hidden" name="payment[rp_dob_month]" value="<?php echo $block->getBirthdayPart('m'); ?>">
            <input type="hidden" name="payment[rp_dob_year]" value="<?php echo $block->getBirthdayPart('Y'); ?>">
        </div>
    <?php endif; ?>
    <div id="ratepay_<?php echo $code; ?>_vatid" class="admin__field" style="margin-top:1.5rem;margin-left:-30px;display: none;">
        <label class="label admin__field-label" for="<?php /* @noEscape */ echo $code; ?>_vatid">
            <span><?php echo $block->escapeHtml(__('Vat ID')); ?></span>
        </label>
        <div class="admin__field-control control">
            <input type="text" size="20" id="<?php echo $code; ?>_vatid" name="payment[rp_vatid]" value="<?php echo $block->getInfoData('rp_vatid'); ?>">
            <input type="hidden" id="<?php echo $code; ?>_company" name="payment[rp_company]" value="<?php echo $block->getInfoData('rp_company'); ?>">
        </div>
    </div>
    <div>
        <?php echo __('ratepay_terms_block_1'); ?> "<?php echo __('Place Order'); ?>" <?php echo __('ratepay_terms_block_2'); ?>
        <a target="_blank" href="https://www.ratepay.com/legal-payment-terms"><?php echo __('ratepay_terms_block_3'); ?></a>
        <?php echo __('ratepay_terms_block_4'); ?>
        <a target="_blank" href="https://www.ratepay.com/legal-payment-dataprivacy"><?php echo __('ratepay_terms_block_5'); ?></a>
        <?php echo __('ratepay_terms_block_6'); ?>
    </div><br>
    <div class="rpContainer">
        <?php if ($block->hasAllowedMonths()): ?>
            <div class="admin__field">
                <?php echo __('rp_calculation_intro_part1'); ?>
                <b><?php echo __('rp_calculation_intro_part2'); ?></b>
                <?php echo __('rp_calculation_intro_part3'); ?>
                <b><?php echo __('rp_calculation_intro_part4'); ?></b>
            </div>
            <div class="admin__field" style="border: 1px solid black; padding: 10px;margin-bottom: 15px;">
                <div class="admin__field" style="margin-top: 0;">
                    <label class="label admin__field-label" for="<?php echo $code.'-time'; ?>">
                        <span><?php echo $block->escapeHtml(__('rp_runtime_description')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <select id="<?php echo $code.'-time'; ?>" onchange="updateInstallmentPlanRuntime('<?php echo $block->getRestUrl(); ?>', <?php echo $ratePayGrandTotal; ?>, '<?php echo $code; ?>')">
                            <option value=""><?php echo __('-- Please select runtime --'); ?></option>
                            <?php foreach ($block->getAllowedMonths() as $value): ?>
                                <option value="<?php echo $value; ?>"><?php echo $value; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="admin__field" style="text-align: center;">
                    <b><?php echo __('---OR---'); ?></b>
                </div>
                <div class="admin__field">
                    <label class="label admin__field-label" for="<?php echo $code.'-rate'; ?>">
                        <span><?php echo $block->escapeHtml(__('rp_rate_description')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input id="<?php echo $code.'-rate'; ?>" type="text" class="form-control" aria-label="Amount" /><br>
                        <span class="input-group-btn">
                            <button id="<?php echo $code.'_Input-button'; ?>" type="button" onclick="updateInstallmentPlanAmount('<?php echo $block->getRestUrl(); ?>', <?php echo $ratePayGrandTotal; ?>, '<?php echo $code; ?>')" class="btn btn-default" role="group">
                                <?php echo __('rp_calculate_rate'); ?>
                            </button>
                        </span>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <input id="<?php echo $code.'-runtime'; ?>" type="hidden" value="" />
        <div class="rpClear"></div>
        <div id="<?php echo $code.'_ContentSwitch'; ?>" class="ratepay-ContentSwitch" style="display: none;">
            <div class="ratepay-ChooseRuntime">
                <div id="<?php echo $code.'_ResultContainer'; ?>">

                </div>
            </div>
        </div>
        <div id="<?php echo $code.'_Notification'; ?>"></div>
    </div>
    <?php if ($block->isSepaBlockVisible() === true): ?>
        <div id="ratepay_rate_sepa_block_<?php echo $code; ?>">
            <ul style="list-style: none; margin-bottom: 15px; border: 1px solid #BDBDBD; padding-left: 4px;">
                <li><label><span><?php echo __('Ratepay address'); ?></span></label></li>
                <li><label><span><?php echo __('Creditor'); ?></span><span><?php echo __('Ratepay Creditor ID'); ?></span></label></li>
                <li><label><span><?php echo __('Mandate'); ?></span><span><?php echo __('Mandate Ref'); ?></span></label></li>
            </ul>
            <ul style="list-style: none;">
                <li style="margin-bottom: 15px;"><label><b><span><?php echo __('insert bankdata'); ?></span></b></label></li>
                <li><label><span><?php echo __('Account holder'); ?></span></label></li>
                <li>
                    <div id="ratepay_<?php echo $code; ?>_accountholder_b2c">
                        <i><span><?php echo $block->getBillingName(); ?></span></i>
                        <input type="hidden" id="ratepay_<?php echo $code; ?>_accountholder_b2c_input" name="payment[rp_accountholder]" value="<?php echo $block->getBillingName(); ?>">
                    </div>
                    <div id="ratepay_<?php echo $code; ?>_accountholder_b2b" style="display: none;">
                        <select id="ratepay_<?php echo $code; ?>_accountholder_b2b_input">
                            <option><?php echo $block->getCompanyName(); ?></option>
                            <option><?php echo $block->getBillingName(); ?></option>
                        </select>
                    </div>
                </li>
            </ul>
            <div class="admin__field _required" style="margin-left: -30px;">
                <label class="label admin__field-label" for="<?php /* @noEscape */ echo $code; ?>_iban" style="margin-left: 11px;">
                    <span><?php echo $block->escapeHtml(__('IBAN')); ?></span>
                </label>
                <div class="admin__field-control control">
                    <input type="text" size="35" id="<?php /* @noEscape */ echo $code; ?>_iban" name="payment[rp_iban]" value="<?php echo $block->getInfoData('rp_iban'); ?>" style="margin-left: 30px;">
                </div>
            </div>
            <a id="<?php echo $code; ?>_sepa_agreement_link" onclick="showAgreement('<?php echo $code; ?>')"><?php echo __('ratepay_directdebit_sepa_link'); ?></a>
            <table>
                <tbody style="display:none;" id="<?php echo $code; ?>_sepa_agreement">
                <tr>
                    <td style="padding:10px 0;">
                            <span class="required ratepayagreement">
                                <?php echo __('ratepay_directdebit_sepa_terms_block_1'); ?>
                                <?php echo __('Ratepay address'); ?>
                                <?php echo __('ratepay_directdebit_sepa_terms_block_2'); ?>
                                <a target="_blank" href="https://www.ratepay.com/legal"><?php echo __('Ratepay Data Privacy Policy'); ?></a>
                                <?php echo __('ratepay_directdebit_sepa_terms_block_3'); ?>
                            </span>
                    </td>
                </tr>
                <tr>
                    <td style="padding:10px 0;">
                        <br/>
                        <span style="font-weight:bold;"><?php echo __('ratepay_directdebit_sepa_notice_block_1'); ?></span><br/>
                        <?php echo __('ratepay_directdebit_sepa_notice_block_2'); ?><br/>
                        <?php echo __('ratepay_directdebit_sepa_notice_block_3'); ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <hr>
        <a id="<?php echo $code; ?>_sepa_use_banktransfer" onclick="showBankTransfer('<?php echo $code; ?>')"><?php echo __('I want to transfer the instalments myself and not pay by direct debit'); ?></a>
        <a id="<?php echo $code; ?>_sepa_use_directdebit" onclick="showDirectDebit('<?php echo $code; ?>')" style="display: none;"><?php echo __('I want to settle the instalments by direct debit'); ?></a>
    <?php endif; ?>
    <input type="hidden" id="<?php echo $code; ?>_directdebit" name="payment[rp_directdebit]" value="1">
    <input type="submit" name="Submit" style="display: none;">
</fieldset>
<script>
    /**
     * Disable card server validation in admin
     */
    require(["Magento_Sales/order/create/form"], function () {
        order.addExcludedPaymentMethod('<?php /* @noEscape */ echo $code; ?>');
    });

    <?php if ($block->hasAllowedMonths() === false): ?>
        require([
            'jquery'
        ], function ($) {
            $(document).ready(function() {
                updateInstallmentPlan('<?php echo $block->getRestUrl(); ?>', 'time', '3', <?php echo $ratePayGrandTotal; ?>, '<?php echo $code; ?>')
            });
        });
    <?php endif; ?>

    ///@TODO: Validierung
    var isInstallmentPlanSet = false;

    <?php if ($b2bEnabled === true): ?>
        require(["jquery"], function ($jq) {
            function handleRequiredData<?php echo $code; ?>() {
                $jq('#<?php echo $code; ?>_company').val($jq('#order-billing_address_company').val());
                if ($jq('#order-billing_address_company').val() == '') {
                    $jq('#ratepay_<?php echo $code; ?>_vatid').hide();
                    $jq('#ratepay_<?php echo $code; ?>_accountholder_b2b').hide();
                    $jq('#ratepay_<?php echo $code; ?>_accountholder_b2c').show();
                    $jq('#ratepay_<?php echo $code; ?>_birthday').show();
                    if (document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2b_input')) {
                        document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2b_input').setAttribute("name","disabled");
                    }
                    if (document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2c_input')) {
                        document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2c_input').setAttribute("name","payment[rp_accountholder]");
                    }
                } else if($jq('#order-billing_address_vat_id').val() == '') {
                    $jq('#ratepay_<?php echo $code; ?>_birthday').hide();
                    $jq('#ratepay_<?php echo $code; ?>_vatid').show();
                    $jq('#ratepay_<?php echo $code; ?>_accountholder_b2c').hide();
                    $jq('#ratepay_<?php echo $code; ?>_accountholder_b2b').show();
                    if (document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2c_input')) {
                        document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2c_input').setAttribute("name","disabled");
                    }
                    if (document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2b_input')) {
                        document.getElementById('ratepay_<?php echo $code; ?>_accountholder_b2b_input').setAttribute("name","payment[rp_accountholder]");
                    }
                } else {
                    if ($jq('#<?php echo $code; ?>_vatid').val() == '') {
                        $jq('#<?php echo $code; ?>_vatid').val($jq('#order-billing_address_vat_id').val());
                    }
                    $jq('#ratepay_<?php echo $code; ?>_birthday').hide();
                    $jq('#ratepay_<?php echo $code; ?>_vatid').hide();
                }
                setTimeout(function(){
                    window.requestAnimationFrame(handleRequiredData<?php echo $code; ?>);
                }, 1000);
            }

            $jq(document).ready(function () {
                handleRequiredData<?php echo $code; ?>();
            });
        });
    <?php endif; ?>
</script>