<?php

$method = $this->getMethodCode();
$result = $this->getInstallmentData();
$notification = null;

?>

<style>
    .rp-installment-plan-details:hover #totalAmount { display: block; }
    .rp-installment-plan-no-details:hover #rate2 { display: block; }
    .rp-installment-plan-details:hover #lastRate { display: block; }
    .rp-installment-plan-details:hover #rate { display: block; }
    .rp-installment-plan-details:hover #interestAmount { display: block; }
    .rp-installment-plan-details:hover #interestRate { display: block; }
    .rp-installment-plan-details:hover #annualPercentageRate { display: block; }
    .rp-installment-plan-details:hover #serviceCharge { display: block; }
    .rp-installment-plan-details:hover #amount { display: block; }
    #rp-hide-installment-plan-details_<?php echo $method; ?> { display: none; }
    #rp-show-installment-plan-details_<?php echo $method; ?> { display: block; }
    #rp-installment-plan-details_<?php echo $method; ?> { display: none; }
    #rp-installment-plan-no-details_<?php echo $method; ?> { display: block; }
</style>

<div class="rp-table-striped">
    <div class="text-center text-uppercase" colspan="2">
        <?php echo __('rp_personal_calculation'); ?>
    </div>
</div>
<?php if (!is_null($notification)) { ?>
    <div>
        <div class="warning small text-center" colspan="2">
            <?php echo __('rp_reason_code_translation_'.$notification); ?><br/>
        </div>
    </div>
<?php } ?>

<div class="rp-menue">
    <div colspan="2" class="small text-right">
        <a class="rp-link" id="rp-show-installment-plan-details_<?php echo $method; ?>" onclick="changeDetails('<?php echo $method; ?>')">
            Zeige Details
            <img src="<?php echo $this->getImageUrl('icon-enlarge.png'); ?>" class="rp-details-icon" />
        </a>
        <a class="rp-link" id="rp-hide-installment-plan-details_<?php echo $method; ?>" onclick="changeDetails('<?php echo $method; ?>')">
            Schließe Details
            <img src="<?php echo $this->getImageUrl('icon-shrink.png'); ?>" class="rp-details-icon" />
        </a>
    </div>
</div>
<div id="rp-installment-plan-details_<?php echo $method; ?>">
    <div class="rp-installment-plan-details">
        <div class="rp-installment-plan-title">
            <?php echo __('rp_cash_payment_price'); ?> <p id="amount" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_cash_payment_price'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['amount']; ?> &euro;
        </div>
    </div>
    <div class="rp-installment-plan-details">
        <div class="rp-installment-plan-title">
            <?php echo __('rp_service_charge'); ?> <p id="serviceCharge" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_service_charge'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['serviceCharge']; ?> &euro;
        </div>
    </div>

    <div class="rp-installment-plan-details">
        <div class="rp-installment-plan-title">
            <?php echo __('rp_effective_rate'); ?> <p id="annualPercentageRate" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_effective_rate'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['annualPercentageRate']; ?> %
        </div>
    </div>

    <div class="rp-installment-plan-details">
        <div class="rp-installment-plan-title">
            <?php echo __('rp_debit_rate'); ?> <p id="interestRate" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_debit_rate'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['interestRate']; ?> %
        </div>
    </div>

    <div class="rp-installment-plan-details">
        <div class="rp-installment-plan-title">
            <?php echo __('rp_interest_amount'); ?> <p id="interestAmount" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_interest_amount'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['interestAmount']; ?> &euro;
        </div>
    </div>

    <div class="rp-installment-plan-details">
        <div colspan="2"></div>
    </div>

    <div class="rp-installment-plan-details">
        <div class="rp-installment-plan-title">
            <?php echo $result['numberOfRates'].' '.__('rp_duration_month'); ?> <p id="rate" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_duration_month'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['rate']; ?> &euro;
        </div>
    </div>

    <div class="rp-installment-plan-details">
        <div class="rp-installment-plan-title">
            <?php echo __('rp_last_rate'); ?> <p id="lastRate" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_last_rate'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['lastRate']; ?> &euro;
        </div>
    </div>
</div>
<div id="rp-installment-plan-no-details_<?php echo $method; ?>">
    <div class="rp-installment-plan-no-details">
        <div class="rp-installment-plan-title">
            <?php echo $result['numberOfRatesFull'].' '.__('rp_duration_month'); ?> <p id="rate2" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_duration_month'); ?></p>
        </div>
        <div class="text-right">
            <?php echo $result['rate']; ?> &euro;
        </div>
    </div>
</div>
<div class="rp-installment-plan-details">
    <div class="rp-installment-plan-title">
        <?php echo __('rp_total_amount'); ?> <p id="totalAmount" class="rp-installment-plan-description small"><?php echo __('rp_mouseover_total_amount'); ?></p>
    </div>
    <div class="text-right">
        <?php echo $result['totalAmount']; ?> &euro;
    </div>
</div>
<?php foreach ($result as $key => $value): ?>
    <input type="hidden" name="payment[rp_<?php echo strtolower($key); ?>]" value="<?php echo $value; ?>">
<?php endforeach; ?>